---
title: "Lego Practice cleaning"
---

```{r}
#install.packages("")
```


```{r}
library(tidyverse)
library(janitor)
```

```{r}
df <- read_csv('./Lego_dataset_cleaned.csv')
df
```
# Unpivot data to a long format for e.g. Tableau report

```{r}
df_pivoted <- df %>% pivot_longer("theme_name_Angry Birds™": "theme_name_Technic",
                    names_to = "theme",
                    values_to = "theme_id") %>% 
  mutate(theme = str_replace_all(theme, "theme_name_", "")) %>% 
  filter(theme_id == 1) %>% 
  pivot_longer("country_AT":"country_US",
               names_to = "country",
               values_to = "country_id") %>% 
  mutate(country = str_replace_all(country, "country_", "")) %>% 
  filter(country_id == 1) %>% 
  pivot_longer(`ages_10+`:`ages_9-16`,
               names_to = "age_group",
               values_to = "age_id") %>% 
  mutate(age_group = str_replace_all(age_group, "ages_", "")) %>% 
  filter(age_id == 1) %>% 
  pivot_longer(`review_difficulty_Average`:`review_difficulty_unknown`,
               names_to = "difficulty",
               values_to = "difficulty_id") %>%
  mutate(difficulty = str_replace_all(difficulty, "review_difficulty_", "")) %>% 
  filter(difficulty_id == 1)

df_pivoted
```

```{r}
df_pivoted <- df_pivoted %>% 
  mutate(theme = str_replace_all(theme, '\231', ''),
         theme = str_replace_all(theme, '®', ''),
         theme = str_to_title(theme))

df_pivoted
```

#Start to summarize the data

```{r}
pivoted <- df_pivoted %>% 
  group_by(age_group, theme) %>% 
  summarize(mean_pieces = mean(piece_count),
            mean_price = mean(list_price),
            mean_val_star = mean(star_rating)) %>% 
  ungroup() %>% 
  arrange(age_group, mean_val_star)

pivoted
```

```{r}
plot(pivoted$mean_price, pivoted$mean_pieces)
```

```{r}
plot(pivoted$mean_price, pivoted$mean_val_star)
```

# So we can begin to see that there is some relationship between the number of pieces
# in a set and the price of the set - which makes sense that the bigger the set, the
# more expensive it is. However, there is not as strong of a relationship between the
# val_star and the price of a set.

```{r}
cor(pivoted$mean_price, pivoted$mean_pieces)
cor(pivoted$mean_price, pivoted$mean_val_star)
```

